### ISSUE TITLE
Crash in hierarchical clusters with euclidean dist with NA values

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/SeqMonk#182]
```
java.lang.NullPointerException
	at uk.ac.babraham.SeqMonk.DataTypes.Cluster.ClusterPair.getConnectedClusters(ClusterPair.java:92)
	at uk.ac.babraham.SeqMonk.DataTypes.Cluster.ClusterPair.getConnectedClusters(ClusterPair.java:92)
	at uk.ac.babraham.SeqMonk.DataTypes.Cluster.ClusterPair.getConnectedClusters(ClusterPair.java:92)
	at uk.ac.babraham.SeqMonk.DataTypes.Cluster.ClusterPair.getConnectedClusters(ClusterPair.java:82)
	at uk.ac.babraham.SeqMonk.Displays.HierarchicalClusterPlot.HierarchicalClusterPanel.setClusterRValue(HierarchicalClusterPanel.java:216)
	at uk.ac.babraham.SeqMonk.Displays.HierarchicalClusterPlot.HierarchicalClusterDialog.stateChanged(HierarchicalClusterDialog.java:329)
	at uk.ac.babraham.SeqMonk.Displays.HierarchicalClusterPlot.HierarchicalClusterDialog.progressComplete(HierarchicalClusterDialog.java:301)
	at uk.ac.babraham.SeqMonk.DataTypes.Cluster.HierarchicalClusterSet.progressComplete(HierarchicalClusterSet.java:112)
	at uk.ac.babraham.SeqMonk.DataTypes.Cluster.HierarchicalClusterSet.run(HierarchicalClusterSet.java:328)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by s-andrews** [comment]
I've added some debugging to try to track this down.  It seems that a ClusterPair object somehow ends up being null.  It's something to do with null values in the quantitation, but it's not clear how.
