### ISSUE TITLE
issue with proxy server

### ISSUE THREAD

**Issue by periv4** [s-andrews/SeqMonk#269]
when trying seqmonk on HPC cluster with proxy server got this error:

Command is: java -Xss4m -Xmx11520m -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true uk.ac.babraham.SeqMonk.SeqMonkApplication 
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 407 Proxy Authentication Required"
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2154)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:195)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1572)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at uk.ac.babraham.SeqMonk.Network.UpdateChecker.getLatestVersionNumber(UpdateChecker.java:128)
	at uk.ac.babraham.SeqMonk.Network.UpdateChecker.isUpdateAvailable(UpdateChecker.java:49)
	at uk.ac.babraham.SeqMonk.Displays.WelcomePanel.SeqMonkInformationPanel.run(SeqMonkInformationPanel.java:518)
	at java.lang.Thread.run(Thread.java:750)

tried set:
System.setProperty("http.proxyUser", "username");
System.setProperty("http.proxyPassword", "xxxxxxxxx");

thanks

**Comment by s-andrews** [comment]
I've been back and looked since this functionality hasn't changed in ages, and I think the issue is that a while back we moved from http to https connections for all of our communication.  Java uses different system properties for https proxies than http ones but the proxy code was never updated.

It should be a simple fix (or addition)

**Comment by s-andrews** [comment]
I hadn't realised we also don't offer authenticated proxies as an option within the preferences.  

As you said that you'd tried adding those two properties you can probably get this working by also setting ```https.proxyHost``` and ```https.proxyPort```

Let me know if that gives you an immediate fix and we'll try to put a friendlier fix into the next release.

**Comment by periv4** [comment]
thanks for you response, i tried and no luck:
Command is: /usr/local/seqmonk/1.48.1/jre/bin/java -Xss4m -Xmx10240m -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dhttp.proxyHost=bmiproxyp.chmcres.cchmc.org -Dhttp.proxyPort=80 -Dhttp.proxyUser=xxxxxxxxx -Dhttp.proxyPassword=xxxxxxxxxx uk.ac.babraham.SeqMonk.SeqMonkApplication 
java.io.IOException: Server returned HTTP response code: 403 for URL: https://www.bioinformatics.babraham.ac.uk/projects/seqmonk/current_version.txt
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at uk.ac.babraham.SeqMonk.Network.UpdateChecker.getLatestVersionNumber(UpdateChecker.java:131)
	at uk.ac.babraham.SeqMonk.Network.UpdateChecker.isUpdateAvailable(UpdateChecker.java:49)
	at uk.ac.babraham.SeqMonk.Displays.WelcomePanel.SeqMonkInformationPanel.run(SeqMonkInformationPanel.java:518)
	at java.base/java.lang.Thread.run(Unknown Source)

is there a way to download the genomes to use it offline, using curl or wget?

Roberto P.

**Comment by s-andrews** [comment]
OK, that's a different error, and different is good!  It looks like it's actually talking to your proxy now and sending your connection instructions.  Is your https proxy really running on port 80 or is there a separate https proxy on port 443.  Does your proxy need you to import a new certificate into your chain of trust to allow it to proxy https connections?

You can manually install genomes from our server if you like.  Take a look at https://github.com/s-andrews/SeqMonk/issues/270 for details.

**Comment by periv4** [comment]
thanks, i was able to bridge a connection without a proxy from another server and download the genome.

Roberto P.
