### ISSUE TITLE
SeqMonk doesn't start under Fedora 27

### ISSUE THREAD

**Issue by s-andrews** [s-andrews/SeqMonk#53]
Even though other X11 apps work we get a crash:

```
CLASSPATH is : /home/thaight/tools/SeqMonk:/home/thaight/tools/SeqMonk/sam-1.32.jar:/home/thaight/tools/SeqMonk/Jama-1.0.2.jar:/home/thaight/tools/SeqMonk/commons-math3-3.5.jar
Prefs file is at: /home/thaight/seqmonk_prefs.txt
Memory ceiling is 10240
Raw physical memory is 15932
Correcting for VM actual requested allocation for 10240 is 11520
Command is: java -Xss4m -Xmx11520m uk.ac.babraham.SeqMonk.SeqMonkApplication
SeqMonk hit a bug - sorry about that.  The crash report is below.
For help with this issue please email the whole of the text of this
report to babraham.bioinformatics@babraham.ac.uk
### BEGIN REPORT ###
java.awt.HeadlessException
java.lang.IllegalStateException: java.awt.HeadlessException
    at uk.ac.babraham.SeqMonk.SeqMonkApplication.main(SeqMonkApplication.java:170)
Caused by: java.awt.HeadlessException
    at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
    at java.awt.Window.<init>(Window.java:536)
    at java.awt.Frame.<init>(Frame.java:420)
    at java.awt.Frame.<init>(Frame.java:385)
    at javax.swing.JFrame.<init>(JFrame.java:189)
    at uk.ac.babraham.SeqMonk.SeqMonkApplication.<init>(SeqMonkApplication.java:190)
    at uk.ac.babraham.SeqMonk.SeqMonkApplication.main(SeqMonkApplication.java:153)
### END REPORT ###
```

**Comment by s-andrews** [comment]
After some digging it turns out this is an issue with the version of java Fedora uses.  Their default install uses a cut-down JRE with all of the graphics integration removed.

If we install the full openjdk with:

sudo yum -y install java-1.8.0-openjdk

Then everything works.

**Comment by s-andrews** [comment]
I'll add a note to the INSTALL.txt file to warn people about this.
